"use client";

import Link from "next/link";
import Image from "next/image";
import { 
  Target, BarChart2, Users, Zap, BookOpen, Brain, 
  GraduationCap, Settings, ArrowRight 
} from "lucide-react";
import { motion } from "framer-motion";

export default function HomePage() {
  const features = [
    {
      title: "Progress Tracking",
      description: "Real-time syllabus coverage tracking with predictive completion models.",
      icon: Target,
    },
    {
      title: "Study Analytics",
      description: "Deep insights into your study patterns, strengths, and areas for improvement.",
      icon: BarChart2,
    },
    {
      title: "Mentor Guidance",
      description: "Direct access to experienced mentors for personalized strategy and feedback.",
      icon: Users,
    },
    {
      title: "Performance Reports",
      description: "Automated weekly and monthly performance analysis generated by AI.",
      icon: Zap,
    },
    {
      title: "Resource Management",
      description: "Organize notes, current affairs, and standard books in one digital vault.",
      icon: BookOpen,
    },
    {
      title: "AI Recommendations",
      description: "Smart suggestions on what topics to revise based on past mock test scores.",
      icon: Brain,
    }
  ];

  return (
    <div className="min-h-screen bg-[#0f141e] text-white font-sans selection:bg-[#00E676]/30">
      
      {/* Header */}
      <header className="sticky top-0 z-50 bg-[#0f141e]/80 backdrop-blur-md border-b border-white/5 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          {/* Logo */}
          <div className="flex items-center bg-white/95 px-3 py-1.5 rounded-lg shadow-sm">
             <Image src="/logo.png" alt="Tracker India Logo" width={140} height={45} className="h-[40px] w-auto object-contain" unoptimized={true} />
          </div>
        </div>
        
        <nav className="hidden md:flex items-center gap-8 text-sm font-semibold text-stone-300">
          <Link href="/" className="text-[#00E676] border-b-2 border-[#00E676] pb-1">Home</Link>
          <Link href="#features" className="hover:text-white transition-colors">Features</Link>
          <Link href="#portals" className="hover:text-white transition-colors">Portals</Link>
        </nav>

        <div>
          <Link href="/register" className="bg-[#00E676] hover:bg-[#00E676]/90 text-[#0f141e] px-6 py-2.5 rounded-full font-bold text-sm transition-all shadow-[0_0_15px_rgba(0,230,118,0.3)]">
            Register
          </Link>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative pt-32 pb-20 px-6 max-w-5xl mx-auto text-center flex flex-col items-center">
        {/* Glow effect behind text */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[400px] bg-[#00E676]/10 blur-[120px] rounded-full pointer-events-none" />

        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-[#00E676]/30 bg-[#00E676]/5 text-[#00E676] text-xs font-semibold mb-8">
          <div className="w-2 h-2 rounded-full bg-[#00E676]" />
          Next-Gen UPSC Preparation Platform
        </div>
        
        <h1 className="text-5xl md:text-7xl font-bold tracking-tight !text-white !font-sans mb-6 leading-tight">
          Tracking System for <br />
          <span className="bg-gradient-to-r from-cyan-400 to-[#00E676] bg-clip-text text-transparent">UPSC Aspirants</span>
        </h1>
        
        <p className="text-stone-400 text-lg md:text-xl max-w-2xl mt-4 mb-12 leading-relaxed">
          Elevate your preparation with data-driven insights, structured mentorship, and intelligent progress tracking. The future of civil services preparation is here.
        </p>
        
        <div className="flex flex-col sm:flex-row items-center gap-4">
          <Link href="/register" className="bg-[#00E676] hover:bg-[#00E676]/90 text-[#0f141e] px-8 py-4 rounded-xl font-bold text-base transition-all flex items-center gap-2 shadow-[0_0_20px_rgba(0,230,118,0.2)] hover:scale-105">
            Get Started Free <ArrowRight className="w-4 h-4" />
          </Link>
          <Link href="#features" className="bg-white/5 hover:bg-white/10 border border-white/10 text-white px-8 py-4 rounded-xl font-bold text-base transition-all">
            Explore Features
          </Link>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-24 px-6 max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold mb-4 !text-white !font-sans">Intelligent Preparation Arsenal</h2>
          <p className="text-stone-400">Everything you need to streamline your UPSC journey, packed into one powerful ecosystem.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, idx) => (
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: idx * 0.1 }}
              key={feature.title} 
              className="bg-[#121824] border border-white/5 hover:border-[#00E676]/50 hover:shadow-[0_0_30px_rgba(0,230,118,0.1)] rounded-2xl p-8 transition-all duration-300 group"
            >
              <div className="w-12 h-12 bg-[#1a212e] rounded-xl flex items-center justify-center mb-6 text-[#00E676] group-hover:scale-110 transition-transform">
                <feature.icon className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold !text-white !font-sans mb-3">{feature.title}</h3>
              <p className="text-stone-400 text-sm leading-relaxed">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Portals Section */}
      <section id="portals" className="py-24 px-6 max-w-6xl mx-auto border-t border-white/5">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold mb-4 !text-white !font-sans">Unified Ecosystem</h2>
          <p className="text-stone-400 text-sm">Dedicated environments tailored for every role in the preparation journey.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Student Portal */}
          <div className="bg-[#121824] border border-white/5 rounded-2xl p-8 flex flex-col hover:border-cyan-400/30 transition-all group">
            <div className="flex items-center gap-4 mb-8 pb-6 border-b border-white/5">
              <div className="w-12 h-12 bg-cyan-500/10 rounded-xl flex items-center justify-center text-cyan-400 group-hover:scale-110 transition-transform">
                <GraduationCap className="w-6 h-6" />
              </div>
              <div>
                <div className="text-cyan-400 text-[10px] font-bold uppercase tracking-widest mb-1">Aspirant</div>
                <h3 className="text-xl font-bold !text-white !font-sans">Student Portal</h3>
              </div>
            </div>
            <ul className="space-y-4 mb-8 text-sm text-stone-400 flex-1">
              <li className="flex items-center gap-3"><div className="w-1.5 h-1.5 bg-cyan-400 rounded-full"/> Daily Task Tracking</li>
              <li className="flex items-center gap-3"><div className="w-1.5 h-1.5 bg-cyan-400 rounded-full"/> Mock Test Analytics</li>
              <li className="flex items-center gap-3"><div className="w-1.5 h-1.5 bg-cyan-400 rounded-full"/> Mentor Interaction</li>
              <li className="flex items-center gap-3"><div className="w-1.5 h-1.5 bg-cyan-400 rounded-full"/> Resource Vault</li>
            </ul>
            <Link href="/login?role=STUDENT" className="w-full py-3.5 bg-white/5 hover:bg-white/10 border border-white/5 rounded-xl text-center text-sm font-semibold transition-colors flex items-center justify-center gap-2">
              Access Portal <ArrowRight className="w-4 h-4" />
            </Link>
          </div>

          {/* Mentor Portal */}
          <div className="bg-[#121824] border border-white/5 rounded-2xl p-8 flex flex-col hover:border-[#00E676]/30 transition-all group">
            <div className="flex items-center gap-4 mb-8 pb-6 border-b border-white/5">
              <div className="w-12 h-12 bg-[#00E676]/10 rounded-xl flex items-center justify-center text-[#00E676] group-hover:scale-110 transition-transform">
                <Users className="w-6 h-6" />
              </div>
              <div>
                <div className="text-[#00E676] text-[10px] font-bold uppercase tracking-widest mb-1">Guide</div>
                <h3 className="text-xl font-bold !text-white !font-sans">Mentor Portal</h3>
              </div>
            </div>
            <ul className="space-y-4 mb-8 text-sm text-stone-400 flex-1">
              <li className="flex items-center gap-3"><div className="w-1.5 h-1.5 bg-[#00E676] rounded-full"/> Student Roster Overview</li>
              <li className="flex items-center gap-3"><div className="w-1.5 h-1.5 bg-[#00E676] rounded-full"/> Performance Review Tools</li>
              <li className="flex items-center gap-3"><div className="w-1.5 h-1.5 bg-[#00E676] rounded-full"/> Session Scheduling</li>
              <li className="flex items-center gap-3"><div className="w-1.5 h-1.5 bg-[#00E676] rounded-full"/> Feedback System</li>
            </ul>
            <Link href="/login?role=MENTOR" className="w-full py-3.5 bg-white/5 hover:bg-white/10 border border-white/5 rounded-xl text-center text-sm font-semibold transition-colors flex items-center justify-center gap-2">
              Access Portal <ArrowRight className="w-4 h-4" />
            </Link>
          </div>

          {/* Admin Portal */}
          <div className="bg-[#121824] border border-white/5 rounded-2xl p-8 flex flex-col hover:border-purple-400/30 transition-all group">
            <div className="flex items-center gap-4 mb-8 pb-6 border-b border-white/5">
              <div className="w-12 h-12 bg-purple-500/10 rounded-xl flex items-center justify-center text-purple-400 group-hover:scale-110 transition-transform">
                <Settings className="w-6 h-6" />
              </div>
              <div>
                <div className="text-purple-400 text-[10px] font-bold uppercase tracking-widest mb-1">Management</div>
                <h3 className="text-xl font-bold !text-white !font-sans">Admin Portal</h3>
              </div>
            </div>
            <ul className="space-y-4 mb-8 text-sm text-stone-400 flex-1">
              <li className="flex items-center gap-3"><div className="w-1.5 h-1.5 bg-purple-400 rounded-full"/> System-Wide Analytics</li>
              <li className="flex items-center gap-3"><div className="w-1.5 h-1.5 bg-purple-400 rounded-full"/> User Management</li>
              <li className="flex items-center gap-3"><div className="w-1.5 h-1.5 bg-purple-400 rounded-full"/> Content Distribution</li>
              <li className="flex items-center gap-3"><div className="w-1.5 h-1.5 bg-purple-400 rounded-full"/> Revenue Tracking</li>
            </ul>
            {/* NO ACCESS BUTTON FOR ADMIN, AS REQUESTED */}
            <div className="w-full py-3.5 opacity-0 cursor-default">
              Hidden Button Placeholder
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-32 px-6 relative overflow-hidden flex justify-center border-t border-white/5">
         <div className="absolute inset-0 bg-[#00E676]/10 blur-[120px] w-[80%] max-w-4xl mx-auto rounded-full pointer-events-none" />
         <div className="relative z-10 text-center">
            <h2 className="text-4xl md:text-5xl font-bold mb-6 !text-white !font-sans">Ready to Transform Your Prep?</h2>
            <p className="text-stone-400 mb-10 text-lg">Join thousands of serious aspirants leveraging data to conquer the examination.</p>
            <Link href="/register" className="bg-[#00E676] hover:bg-[#00E676]/90 text-[#0f141e] px-10 py-4 rounded-full font-bold text-base transition-all shadow-[0_0_20px_rgba(0,230,118,0.4)]">
              Join UPSC Aspirants Community
            </Link>
         </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/10 bg-[#0a0d14] py-16 px-6">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between gap-12">
           <div className="max-w-sm">
             <div className="flex items-center gap-2 mb-6">
                <div className="opacity-90 hover:opacity-100 transition-opacity bg-white/95 px-4 py-2 rounded-xl shadow-sm inline-block">
                   <Image src="/logo.png" alt="Tracker India Logo" width={120} height={38} className="h-[38px] w-auto object-contain" unoptimized={true} />
                </div>
             </div>
             <p className="text-stone-500 text-sm leading-relaxed">
               The ultimate data-driven tracking system for UPSC Aspirants. Elevating preparation through data-driven insights and smart tools.
             </p>
           </div>
           
           <div className="flex gap-16">
             <div>
               <h4 className="font-bold !text-white !font-sans mb-6 text-sm uppercase tracking-widest">Quick Links</h4>
               <ul className="space-y-4 text-sm text-stone-500">
                 <li><Link href="/" className="hover:text-[#00E676] transition-colors">Home</Link></li>
                 <li><Link href="#features" className="hover:text-[#00E676] transition-colors">Features</Link></li>
                 <li><Link href="#portals" className="hover:text-[#00E676] transition-colors">Portals</Link></li>
               </ul>
             </div>
             <div>
               <h4 className="font-bold !text-white !font-sans mb-6 text-sm uppercase tracking-widest">Contact Us</h4>
               <ul className="space-y-4 text-sm text-stone-500">
                 <li className="hover:text-white transition-colors">support@trackerindia.com</li>
                 <li className="hover:text-white transition-colors">+91 99999 99999</li>
                 <li className="hover:text-white transition-colors">New Delhi, India</li>
               </ul>
             </div>
           </div>
        </div>
      </footer>

    </div>
  );
}
