"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  Trophy, 
  Clock, 
  HelpCircle, 
  ChevronRight, 
  ChevronLeft, 
  CheckCircle2, 
  AlertTriangle,
  Loader2,
  BookOpen
} from "lucide-react";

interface Question {
  question: string;
  statements: string[];
  options: string[];
  correctAnswer: number;
  explanation: string;
}

export default function ProductivityTest() {
  const [subject, setSubject] = useState("");
  const [exam, setExam] = useState("UPSC");
  const [started, setStarted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [userAnswers, setUserAnswers] = useState<number[]>([]);
  const [timeLeft, setTimeLeft] = useState(1200); // 20 mins
  const [isFinished, setIsFinished] = useState(false);

  const startTest = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/ai/generate-test", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ subject, exam, count: 10 }), // 10 for quick testing
      });
      const data = await res.json();
      
      if (!res.ok) {
        throw new Error(data.error || "Failed to generate test. The AI might be overloaded.");
      }

      setQuestions(data.questions || data); // Handle both wrapped and unwrapped JSON
      setStarted(true);
      setUserAnswers(new Array(data.questions?.length || data.length).fill(-1));
    } catch (error: any) {
      console.error("Test generation error:", error);
      setError(error.message || "Failed to start test due to high AI demand. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (started && timeLeft > 0 && !isFinished) {
      const timer = setTimeout(() => setTimeLeft(timeLeft - 1), 1000);
      return () => clearTimeout(timer);
    } else if (timeLeft === 0) {
      setIsFinished(true);
    }
  }, [started, timeLeft, isFinished]);

  const handleAnswer = (index: number) => {
    const newAnswers = [...userAnswers];
    newAnswers[currentIndex] = index;
    setUserAnswers(newAnswers);
  };

  const calculateScore = () => {
    let score = 0;
    userAnswers.forEach((ans, idx) => {
      if (ans === questions[idx].correctAnswer) score++;
    });
    return score;
  };

  if (!started) {
    return (
      <div className="max-w-2xl mx-auto p-12 bg-white border border-border shadow-xl">
        <BookOpen className="w-16 h-16 text-primary mb-6" />
        <h2 className="text-3xl font-serif font-bold text-primary mb-4">Start Productivity Test</h2>
        <p className="text-muted-foreground mb-8">Generated by AI to test your current retention and conceptual depth.</p>
        
        <div className="space-y-6">
          <div className="space-y-2">
            <label className="text-xs font-bold uppercase tracking-widest">Select Subject</label>
            <select 
              className="w-full p-4 border border-border focus:border-primary outline-none"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
            >
              <option value="">-- Choose Subject --</option>
              <option value="History">History</option>
              <option value="Polity">Polity (Laxmikanth Standard)</option>
              <option value="Economy">Economy</option>
              <option value="Geography">Geography</option>
              <option value="Current Affairs">Today's Current Affairs (The Hindu)</option>
            </select>
          </div>
          
          {error && (
            <div className="p-4 bg-red-50 text-red-600 border border-red-200 text-sm font-medium flex items-start gap-2">
              <AlertTriangle className="w-5 h-5 flex-shrink-0" />
              <span>{error}</span>
            </div>
          )}

          <button
            disabled={!subject || loading}
            onClick={startTest}
            className="w-full bg-primary text-white p-4 font-bold uppercase tracking-widest flex items-center justify-center gap-2 hover:bg-primary/90 transition-all disabled:opacity-50"
          >
            {loading ? <Loader2 className="animate-spin" /> : "Generate & Start Test"}
          </button>
        </div>
      </div>
    );
  }

  if (isFinished) {
    const score = calculateScore();
    const accuracy = (score / questions.length) * 100;

    return (
      <div className="max-w-4xl mx-auto space-y-8 print:max-w-none print:w-full print:m-0 print:p-0">
        <div className="bg-white p-10 border border-border shadow-xl text-center print:shadow-none print:border-none print:p-0 print:mb-8">
          <Trophy className="w-16 h-16 text-accent mx-auto mb-4 print:hidden" />
          <h2 className="text-4xl font-serif font-bold text-primary mb-2 print:text-black">Test Completed</h2>
          <p className="text-muted-foreground print:text-black">Accuracy: {accuracy.toFixed(1)}% • Time Taken: {Math.floor((1200 - timeLeft) / 60)}m</p>
          
          <div className="mt-8 grid grid-cols-3 gap-4 print:hidden">
            <div className="p-4 bg-muted/30">
              <span className="block text-2xl font-bold">{score}</span>
              <span className="text-[10px] uppercase font-bold text-muted-foreground tracking-tighter">Correct</span>
            </div>
            <div className="p-4 bg-muted/30">
              <span className="block text-2xl font-bold">{questions.length - score}</span>
              <span className="text-[10px] uppercase font-bold text-muted-foreground tracking-tighter">Incorrect</span>
            </div>
            <div className="p-4 bg-accent/10">
              <span className="block text-2xl font-bold text-accent">{score * 2}</span>
              <span className="text-[10px] uppercase font-bold text-accent tracking-tighter">Points</span>
            </div>
          </div>

          <div className="mt-8 flex justify-center print:hidden">
            <button 
              onClick={() => window.print()} 
              className="px-6 py-3 bg-stone-900 text-white font-bold uppercase tracking-widest text-xs flex items-center gap-2 hover:bg-stone-800 transition-all"
            >
              <BookOpen className="w-4 h-4" />
              Download Q&A (PDF)
            </button>
          </div>
        </div>

        <div className="space-y-6 print:space-y-4">
          <h3 className="text-xl font-serif font-bold text-primary print:text-black">Analysis & Explanations</h3>
          {questions.map((q, idx) => (
            <div key={idx} className={`p-8 bg-white border print:p-0 print:border-none print:mb-6 print:break-inside-avoid ${userAnswers[idx] === q.correctAnswer ? "border-green-200" : "border-red-200"}`}>
              <div className="flex gap-4 items-start mb-4">
                <span className="bg-primary text-white w-8 h-8 flex items-center justify-center flex-shrink-0 text-xs font-bold print:border print:border-black print:bg-white print:text-black">{idx + 1}</span>
                <h4 className="font-bold text-foreground print:text-black">{q.question}</h4>
              </div>
              <ul className="ml-12 space-y-2 mb-6">
                {q.statements.map((s, si) => (
                  <li key={si} className="text-sm text-foreground/80">• {s}</li>
                ))}
              </ul>
              <div className="ml-12 p-4 bg-slate-50 text-sm">
                <p className="font-bold text-primary mb-2 flex items-center gap-2">
                  <HelpCircle className="w-4 h-4" /> Official Explanation:
                </p>
                <p className="text-muted-foreground italic leading-relaxed">{q.explanation}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  const q = questions[currentIndex];

  return (
    <div className="max-w-4xl mx-auto flex flex-col gap-8">
      {/* Test Header */}
      <div className="flex justify-between items-center bg-white p-4 border border-border shadow-md">
        <div className="flex items-center gap-4">
          <span className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Progress</span>
          <div className="w-48 h-2 bg-muted rounded-full overflow-hidden">
            <div className="h-full bg-primary" style={{ width: `${((currentIndex + 1) / questions.length) * 100}%` }} />
          </div>
          <span className="text-xs font-bold">{currentIndex + 1} / {questions.length}</span>
        </div>
        <div className="flex items-center gap-3 bg-red-50 text-red-700 px-4 py-2 rounded border border-red-100">
          <Clock className="w-5 h-5" />
          <span className="font-mono font-bold">
            {Math.floor(timeLeft / 60)}:{String(timeLeft % 60).padStart(2, '0')}
          </span>
        </div>
      </div>

      {/* Question Area */}
      <div className="bg-white p-12 border border-border shadow-2xl relative min-h-[400px]">
        <div className="mb-10">
          <h3 className="text-2xl font-serif font-bold text-primary leading-snug mb-8">{q.question}</h3>
          <ul className="space-y-4">
            {q.statements.map((s, idx) => (
              <li key={idx} className="flex gap-4 items-start text-foreground/90 leading-relaxed font-medium">
                <span className="text-primary font-bold">{idx + 1}.</span> {s}
              </li>
            ))}
          </ul>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {q.options.map((opt, idx) => (
            <button
              key={idx}
              onClick={() => handleAnswer(idx)}
              className={`p-4 text-left border-2 transition-all flex items-center justify-between ${
                userAnswers[currentIndex] === idx 
                  ? "border-primary bg-primary/5 shadow-inner" 
                  : "border-border hover:border-primary/20"
              }`}
            >
              <span className="font-bold text-sm">{opt}</span>
              {userAnswers[currentIndex] === idx && <CheckCircle2 className="w-5 h-5 text-primary" />}
            </button>
          ))}
        </div>
      </div>

      {/* Navigation Buttons */}
      <div className="flex justify-between">
        <button
          disabled={currentIndex === 0}
          onClick={() => setCurrentIndex(currentIndex - 1)}
          className="px-6 py-3 border border-primary text-primary font-bold uppercase text-xs tracking-widest hover:bg-primary/5 transition-all disabled:opacity-30"
        >
          <ChevronLeft className="w-4 h-4 inline mr-2" /> Previous
        </button>
        
        {currentIndex === questions.length - 1 ? (
          <button
            disabled={loading}
            onClick={async () => {
              setLoading(true);
              const score = calculateScore();
              const accuracy = (score / questions.length) * 100;
              try {
                await fetch("/api/ai/save-test", {
                  method: "POST",
                  headers: { "Content-Type": "application/json" },
                  body: JSON.stringify({
                    subject,
                    score,
                    totalQuestions: questions.length,
                    accuracy,
                    timeTaken: 1200 - timeLeft,
                    weakAreas: "Need to review explanations"
                  })
                });
              } catch (e) {
                console.error(e);
              }
              setLoading(false);
              setIsFinished(true);
            }}
            className="px-8 py-3 bg-accent text-accent-foreground font-bold uppercase text-xs tracking-widest shadow-lg disabled:opacity-50 flex items-center gap-2"
          >
            {loading && <Loader2 className="w-4 h-4 animate-spin" />} Submit Exam
          </button>
        ) : (
          <button
            onClick={() => setCurrentIndex(currentIndex + 1)}
            className="px-8 py-3 bg-primary text-white font-bold uppercase text-xs tracking-widest shadow-lg"
          >
            Next Question <ChevronRight className="w-4 h-4 inline ml-2" />
          </button>
        )}
      </div>
    </div>
  );
}
